import { UserSettings, CustomTag } from '../types';

export function createDefaultUserSettings(userId = 'default_user_1', accountId?: string): UserSettings {
  return {
    id: accountId ? `set_${userId}_${accountId}` : `set_${userId}`,
    userId,
    accountId,
    scope: accountId ? 'ACCOUNT' : 'GLOBAL',
    general: {
      theme: 'dark',
      accentColor: '#3B82F6',
      density: 'comfortable',
      chartAnimations: true,
      reducedMotion: false,
      currency: 'USD',
      currencyMode: 'USD',
      numberFormat: 'en-US',
      decimalPrecision: 2,
      percentagePrecision: 2,
      roundingBehavior: 'round',
      timezone: 'America/New_York',
      dateFormat: 'YYYY-MM-DD',
      timeFormat: '12h',
      firstDayOfWeek: 'Sunday',
      calendarTimezone: 'America/New_York',
      sessionTimezone: 'America/New_York',
    },
    notifications: {
      tradeAlerts: true,
      riskAlerts: true,
      propFirmWarnings: true,
      syncNotifications: true,
      dailyJournalReminder: true,
      weeklyPerformanceReview: true,
      soundEnabled: true,
    },
    aiSettings: {
      aiCoachEnabled: true,
      responseStyle: 'institutional',
      analysisScope: 'all',
      autoReviewTrades: true,
    },
    tradeDefaults: {
      defaultAccountId: '',
      defaultMarket: 'Futures',
      defaultDirection: 'BUY',
      defaultOrderType: 'MARKET',
      defaultQuantity: 1,
      defaultRiskValue: 1.0,
      defaultRiskUnit: 'PERCENT',
      defaultStopLossBehavior: 'POINTS',
      defaultTakeProfitBehavior: 'R_TARGET',
      defaultRTarget: 2.0,
      maxPlannedRisk: 500,
      defaultSetup: 'Opening Drive',
      defaultPlaybookId: '',
      defaultSession: 'New York',
      defaultStatus: 'CLOSED',
      requireSetup: false,
      requireStopLoss: false,
      requireTakeProfit: false,
      requireNotes: false,
      requireScreenshot: false,
      requireMistakeOnLoss: false,
      allowPartialExits: true,
      allowMultipleEntries: true,
      allowMultipleExits: true,
      trackCommissions: true,
      trackSwapFees: true,
      trackSlippage: false,
      defaultTableColumns: ['date', 'symbol', 'direction', 'market', 'entryPrice', 'exitPrice', 'netPnl', 'rMultiple', 'status'],
      defaultTradeSort: 'date_desc',
    },
    commissionRules: [
      {
        id: 'cr-default-futures',
        account: 'ALL',
        instrument: 'Futures',
        symbol: 'ALL',
        mode: 'Per Contract',
        apply: 'Round-Trip',
        commission: 2.50,
        exchangeFee: 1.25,
        clearingFee: 0.20,
        platformFee: 0.50,
        otherFee: 0,
      },
      {
        id: 'cr-default-forex',
        account: 'ALL',
        instrument: 'Forex',
        symbol: 'ALL',
        mode: 'Per Lot',
        apply: 'Round-Trip',
        commission: 3.50,
        exchangeFee: 0,
        clearingFee: 0,
        platformFee: 0,
        otherFee: 0,
      },
      {
        id: 'cr-default-stocks',
        account: 'ALL',
        instrument: 'Stocks',
        symbol: 'ALL',
        mode: 'Per Share',
        apply: 'Both Sides',
        commission: 0.005,
        exchangeFee: 0.001,
        clearingFee: 0.0005,
        platformFee: 0,
        otherFee: 0,
      },
      {
        id: 'cr-default-crypto',
        account: 'ALL',
        instrument: 'Crypto',
        symbol: 'ALL',
        mode: 'Percentage',
        apply: 'Both Sides',
        commission: 0.05,
        exchangeFee: 0,
        clearingFee: 0,
        platformFee: 0,
        otherFee: 0,
      },
    ],
    profile: {
      bio: 'Quantitative price action trader specializing in index futures and momentum breakouts.',
      country: 'United States',
      professionalTitle: 'Independent Prop Trader',
      phone: '',
      tradingStyle: 'Day Trader',
    },
  };
}

export const DEFAULT_TAGS_FALLBACK: CustomTag[] = [
  { id: 'tag-1', name: 'A+ Setup', category: 'Setup', color: '#10B981', description: 'Optimal execution matching all playbook rules perfectly', createdAt: new Date().toISOString() },
  { id: 'tag-2', name: 'Opening Drive', category: 'Setup', color: '#3B82F6', description: 'Aggressive opening bell market auction trend', createdAt: new Date().toISOString() },
  { id: 'tag-3', name: 'Revenge Trading', category: 'Mistake', color: '#EF4444', description: 'Impulsive entry following a loss without a valid signal', createdAt: new Date().toISOString() },
  { id: 'tag-4', name: 'FOMO', category: 'Psychology', color: '#F59E0B', description: 'Fear of missing out on rapid price movement', createdAt: new Date().toISOString() },
  { id: 'tag-5', name: 'Breakout', category: 'Market', color: '#8B5CF6', description: 'Key support/resistance level expansion', createdAt: new Date().toISOString() },
  { id: 'tag-6', name: 'Early Exit', category: 'Execution', color: '#EC4899', description: 'Closed position prematurely prior to target', createdAt: new Date().toISOString() },
  { id: 'tag-7', name: 'Moved Stop', category: 'Mistake', color: '#DC2626', description: 'Violated risk parameters by shifting stop loss further', createdAt: new Date().toISOString() },
  { id: 'tag-8', name: 'Disciplined', category: 'Psychology', color: '#06B6D4', description: 'Flawless mental focus and rule compliance', createdAt: new Date().toISOString() },
  { id: 'tag-9', name: 'Clean Trend', category: 'Market', color: '#14B8A6', description: 'Clear directional sequence of higher highs/lower lows', createdAt: new Date().toISOString() },
  { id: 'tag-10', name: 'News Volatility', category: 'Market', color: '#6366F1', description: 'CPI, FOMC, or economic report catalyst', createdAt: new Date().toISOString() },
];
