export interface CountryItem {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: CountryItem[] = [
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
];

export const TIMEZONES = [
  { id: 'America/New_York', value: 'America/New_York', label: 'America/New_York (EST/EDT - US Equities/CME)' },
  { id: 'America/Chicago', value: 'America/Chicago', label: 'America/Chicago (CST/CDT - Chicago Pit)' },
  { id: 'America/Los_Angeles', value: 'America/Los_Angeles', label: 'America/Los_Angeles (PST/PDT - US West)' },
  { id: 'America/Toronto', value: 'America/Toronto', label: 'America/Toronto (EST/EDT - TSX)' },
  { id: 'America/Sao_Paulo', value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (BRT - B3 Brazil)' },
  { id: 'Europe/London', value: 'Europe/London', label: 'Europe/London (GMT/BST - LSE & London FX)' },
  { id: 'Europe/Frankfurt', value: 'Europe/Frankfurt', label: 'Europe/Frankfurt (CET/CEST - Eurex & DAX)' },
  { id: 'Europe/Paris', value: 'Europe/Paris', label: 'Europe/Paris (CET/CEST - Euronext)' },
  { id: 'Europe/Zurich', value: 'Europe/Zurich', label: 'Europe/Zurich (CET/CEST - SIX Swiss)' },
  { id: 'Europe/Amsterdam', value: 'Europe/Amsterdam', label: 'Europe/Amsterdam (CET/CEST - AEX)' },
  { id: 'Asia/Dubai', value: 'Asia/Dubai', label: 'Asia/Dubai (GST - Dubai DFM/ADX)' },
  { id: 'Asia/Kolkata', value: 'Asia/Kolkata', label: 'Asia/Kolkata (IST - NSE & BSE India)' },
  { id: 'Asia/Singapore', value: 'Asia/Singapore', label: 'Asia/Singapore (SGT - SGX & Asia FX)' },
  { id: 'Asia/Hong_Kong', value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (HKT - HKEX)' },
  { id: 'Asia/Tokyo', value: 'Asia/Tokyo', label: 'Asia/Tokyo (JST - TSE & Nikkei)' },
  { id: 'Asia/Shanghai', value: 'Asia/Shanghai', label: 'Asia/Shanghai (CST - SSE/SZSE)' },
  { id: 'Asia/Seoul', value: 'Asia/Seoul', label: 'Asia/Seoul (KST - KRX Korea)' },
  { id: 'Australia/Sydney', value: 'Australia/Sydney', label: 'Australia/Sydney (AEST/AEDT - ASX)' },
  { id: 'Pacific/Auckland', value: 'Pacific/Auckland', label: 'Pacific/Auckland (NZST/NZDT - NZX)' },
  { id: 'UTC', value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
];

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar', label: 'USD ($) - US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro', label: 'EUR (€) - Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound', label: 'GBP (£) - British Pound' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', label: 'JPY (¥) - Japanese Yen' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', label: 'AUD (A$) - Australian Dollar' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', label: 'CAD (C$) - Canadian Dollar' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', label: 'CHF (CHF) - Swiss Franc' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', label: 'INR (₹) - Indian Rupee' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', label: 'SGD (S$) - Singapore Dollar' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', label: 'HKD (HK$) - Hong Kong Dollar' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', label: 'NZD (NZ$) - New Zealand Dollar' },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham', label: 'AED (AED) - UAE Dirham' },
];
